# Generated by Django 3.2.7 on 2021-10-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.CharField(default='subtitulo', max_length=50, null=True)),
                ('description_1', models.TextField(max_length=300, null=True)),
                ('description_2', models.TextField(blank=True, max_length=300, null=True)),
                ('main_img', models.ImageField(null=True, upload_to='image/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact', max_length=50, null=True)),
                ('subtitle', models.CharField(default='Our Social Links', max_length=100, null=True)),
                ('wsp_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=40, null=True)),
                ('logo', models.ImageField(null=True, upload_to='image/')),
                ('text', models.TextField(max_length=500, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, null=True)),
                ('header', models.CharField(max_length=50, null=True)),
                ('subheader', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Youtube_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='nombre de cancion', max_length=50)),
                ('artist_name', models.CharField(default='artista', max_length=50)),
                ('youtube_url', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
                ('artist_img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='nombre de cancion', max_length=50)),
                ('artist_name', models.CharField(default='artista', max_length=50)),
                ('spotify_url', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
                ('artist_img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='nombre de playlist', max_length=50)),
                ('spotify_url', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
                ('artist_img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='nombre de album', max_length=50)),
                ('artist_name', models.CharField(default='artista', max_length=50)),
                ('spotify_url', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
                ('artist_img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Slider_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='image/')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.services')),
            ],
            options={
                'verbose_name_plural': 'slider_services',
            },
        ),
        migrations.CreateModel(
            name='Slider_Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='image/')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.services')),
            ],
            options={
                'verbose_name_plural': 'Slider_Facilities',
            },
        ),
        migrations.CreateModel(
            name='Slider_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='image/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardinpage.about')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jardinero', models.CharField(max_length=50)),
                ('acerca', models.TextField(max_length=100, null=True)),
                ('social_link', models.URLField(blank=True, null=True)),
                ('profile_img', models.ImageField(upload_to='profile/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardinpage.about')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='instalaciones como equipo y salas de ensayo', max_length=30, null=True)),
                ('description', models.TextField(default='describir instalaciones y equipo del estudio', max_length=300, null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.services')),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('main_img', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=300, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('net_color', models.CharField(default='#5bc0de', max_length=10)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='servicio que se brinda', max_length=30, null=True)),
                ('description', models.TextField(default='descripcion del servicio', max_length=300, null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.services')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='AssociateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('main_img', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=300, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardinpage.contact')),
            ],
        ),
    ]
